### ISSUE TITLE
tidak bisa menampilkan perhar dan per bulan

### ISSUE THREAD

**Issue by muhammadyana** [bachors/Pray-Times-API#1]
thank gan udah share. 
tapi untuk API yg sekarang belum bisa tampil perhari dan perbulan. 
tolong di update ya gan, hehe

**Comment by bachors** [comment]
sudah gan 👍

**Comment by muhammadyana** [comment]
sip mantap gan.. 
thanks. 
kalo bisa sih jadawalnya disamain sama yg di http://sihat.kemenag.go.id/waktu-sholat 
mereka punya kalkulasi sendiri
